apiVersion: v1
kind: Service
metadata:
  name: aceestapp-service
spec:
  selector:
    app: aceestapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer   # or NodePort if you’re testing locally
